averages = 1

[acquisition_instruments.Daq1]
name = "Daq1"
instrument = "NIDAQ_Base"

[scan_instruments.SG1]
name = "SG1"
instrument = "SG380"

[scan_collection.SG1-frequency]
instrument = "SG380"
parameter = "frequency"
min = 1
max = 2
points = 10
repetitions = 1
scale = "linear"
randomize = "False"
note = ""
name = "SG1"

[acquisition_instruments.Daq1.parameters]
device_name = "Dev1"
read_sample_rate = 50000.0
read_sample_rate_out = 1000.0
read_samples_per_chan = 10000.0
reads_per_sample = 1
read_samples_total = 10000.0
read_channels = [ "ai1",]

[acquisition_instruments.Daq1.latent_parameters]
units = "volts"
voltage_limits = 2
terminal_type = "RSE"
read_clock_source = "OnboardClock"
read_active_edge = "rising_edge"
read_sample_mode = "finite_samples"
read_timeout = "infinite_timeout"
read_trigger_channel = "PFI0"
read_fill_mode = "by_channel"

[acquisition_instruments.Daq1.preparations]
read = [ "analog_input",]
read_method = "analog_input"

[scan_instruments.SG1.parameters]
frequency = 2800000000.0
phase = 0
amplitude = 0.0
modulation = "Off"
modulation_Source = "External"

[scan_instruments.SG1.latent_parameters]
IPaddress = "10.229.42.86"
port = "5025"
