name = "SG1"
device = "SG380"

[parameters]
frequency = 2870.0
phase = 0
amplitude = -3.0
enabled = false
modulation_enabled = false
modulation_type = "IQ"
modulation_function = "External"
modulation_dev = 0
modulation_rate = 0

[latent_parameters]
IPaddress = "10.229.42.86"
port = "5025"
read_termination = "r\n"
