name = "SG1"

device = "SG380"

[parameters]
frequency = 2.8e3
phase = 0
amplitude = 0.0
modulation_enabled = false
modulation_type = 'IQ'
modulation_function = 'External'

[latent_parameters]
IPaddress = '10.229.42.86'
port = '5025'

## Alternatively use GPIB
## GPIB = '27'