name = 'Daq1'

device = 'NIDAQ_Base'

[parameters]
device_name = "Dev1"
input_sample_rate = 50000.0
input_sample_rate_out = 1000.0
input_samples_per_chan = 10000.0
inputs_per_sample = 1
input_samples_total = 10000.0
input_channels = ['ai1']

[latent_parameters]
units = "volts"
voltage_limits = 2
terminal_type = "RSE"
input_clock_source = "OnboardClock"
input_active_edge = "rising_edge"
input_sample_mode = "finite_samples"
input_timeout = "infinite_timeout"
input_trigger_channel = 'PFI0'
input_fill_mode = 'by_channel'

[preparations]
input = ['analog_input']
input_method = 'analog_input'