name = "Daq1"
device = "NIDAQ_Base"

[parameters]
device_name = "Dev1"
read_sample_rate = 50000.0
read_samples_per_chan = 10000.0
reads_per_sample = 1
read_samples_total = 10000
read_channels = [ "ai1",]
write_sample_rate = 5000.0
write_samples_per_chan = 1000.0
writes_per_sample = 1
write_samples_total = 1000.0
write_channels = []
read_sample_rate_out = 1000.0

[latent_parameters]
units = "volts"
voltage_limits = 2
terminal_type = "RSE"
read_clock_source = "OnboardClock"
read_active_edge = "rising_edge"
read_sample_mode = "finite_samples"
read_fill_mode = "by_channel"
read_timeout = "infinite_timeout"
read_trigger_channel = "PFI0"
write_units = "volts"
write_voltage_limits = "10"
write_sample_mode = "finite_samples"
write_clock_source = "OnBoardClock"
write_trigger_edge = "rising_edge"
write_fill_mode = "by_scan"

[preparations]
input = [ "analog_input",]
input_method = "analog_input"
